### ISSUE TITLE
Any plan to support Xplane 12?

### ISSUE THREAD

**Issue by pianista215** [waynepiekarski/XPlaneCDU#13]
Hi!

I'm really impressed with the code, and if you are open for collaboration and you give me some advises, I can help you to migrate the current code for Xp12 or supporting new planes.

For example, I was thinking in supporting Airfoillabs King air 350 that is one I usually use, but also other you can think are interesting :)

Regards

**Comment by waynepiekarski** [comment]
XPlaneCDU uses the ExtPlane plugin to get access to all the internal datarefs in X-Plane. My understanding is that existing plugins like this work fine with the 11 to 12 migration and there isn't anything that needs to be done. Do you know of any bugs on XP12?

I was able to support both the Zibo 737 and SSG 747 since they used a similar way of representing the CDU, so able to do this without making too much of the code aircraft specific. However I never got around to doing Laminar's CDU because the datarefs were structured differently. It might have been easier just to fork the code and change everything needed for that one aircraft. So I'm not sure about the King Air, but forking might be easier than putting in a few if() statements, so just keep that in mind.

**Comment by pianista215** [comment]
Ok thank you for clarifying, it seems that although problems with the ExtPlane plugin, all should work perfect :)
